language: node_js
cache: yarn
node_js:
  - 8.10.0
before_install:
  - npm install -g yarn
script:
  - yarn test
before_deploy: 
  - npm install serverless -g
  - sls config credentials -p aws -k $AWS_KEY -s $AWS_SECRET -o
deploy:
  - provider: script
    script: sls deploy -s prod
    skip-cleanup: true
    keep-history: true
    on:
      branch: master
  - provider: script
    script: sls deploy -s dev
    skip-cleanup: true
    keep-history: true
    on:
      branch: develop